name: testing_adv
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # localization helper
  intl: ^0.17.0
  # localization automation
  intl_utils: ^2.4.0
  # custom fonts
  google_fonts: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.1.0
  # project workflow automation
  build_runner: ^2.1.2
  #mocking
  mocktail: ^0.2.0
  #mocking nav
  mockingjay: ^0.1.1
  #bdd widget testing
  given_when_then: ^0.2.0
  # hamcrest style matchers
  matcher: ^0.12.11




  flutter_lints: ^1.0.0

dependency_overrides:
  #to force mockjay to mocktail 2.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - google_fonts/
    - images/
# flutter intl for localization settings
flutter_intl:
  enabled: true   
  class_name: S   
  main_locale: en 
  arb_dir: lib/src/localization
  output_dir: lib/src/localization_gen
  use_deferred_loading: false

